# пользователь
USERNAME_MAX_LENGTH = 64
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
REGULAR_USERNAME = r'^[\w.@+-]+\Z'
MY_USER_PROFILE = 'me'

# рецепты
MAX_LENGTH_INGREDIENT_NAME = 256
MAX_LENGTH_MEASUREMENT_UNIT = 20
MAX_LENGTH_TAG = 30
MAX_LENGTH_TAG_SLUG = 64
MAX_LENGTH_RECIPES_NAME = 256
STR_LENGTH = 31
MAX_DIGITS_AMOUNT = 9
MAX_PLACES_AMOUNT = 3
