# Generated by Django 5.2.6 on 2025-10-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_recipes_options_alter_recipes_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='tag',
            new_name='tags',
        ),
    ]
