# Generated by Django 5.2.6 on 2025-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='foodgram.tag', verbose_name='Метка'),
        ),
    ]
