# Generated by Django 5.2.6 on 2025-10-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_recipes_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': 'ingredient_amounts', 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='foodgram.tag', verbose_name='Метка'),
        ),
    ]
