# Generated by Django 5.2.6 on 2025-10-04 16:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_ingredients_options_rename_tag_recipes_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.MinValueValidator(0.01, 'Количество должно быть больше нуля')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не меньше 1 минуты')], verbose_name='Время приготовления в минутах'),
        ),
    ]
