# Generated by Django 5.2.6 on 2025-10-13 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0006_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не меньше 1 минуты')], verbose_name='Время (мин)'),
        ),
    ]
