# Generated by Django 5.2.6 on 2025-10-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0007_alter_recipes_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': 'ingredient_amounts', 'verbose_name': 'Продукт рецепта', 'verbose_name_plural': 'Продукты рецепта'},
        ),
    ]
