# Generated by Django 5.2.6 on 2025-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0010_alter_ingredientamount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': 'ingredient_amounts', 'verbose_name': 'Количество продукта в рецепте', 'verbose_name_plural': 'Количества продуктов в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'default_related_name': 'recipes', 'ordering': ('-created_at',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
