# Generated by Django 5.2.6 on 2025-10-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0011_alter_ingredientamount_options_alter_recipes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': 'ingredient_amounts', 'verbose_name': 'Количество продукта в рецепте', 'verbose_name_plural': 'Количество продуктов в рецептах'},
        ),
    ]
