USERNAME_MAX_LENGTH = 64
EMAIL_MAX_LENGTH = 254
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
REGULAR_USERNAME = r'^[\w.@+-]+\Z'
ERROR_USERNAME_SYMBOLS = (
    'Имя пользователя может содержать'
    'буквы, цифры, и некоторые знаки'
)

MAX_LENGTH_INGREDIENT_NAME = 256
MAX_LENGTH_MEASUREMENT_UNIT = 5
MAX_LENGTH_TAG = 7
MAX_LENGTH_TAG_SLUG = 9
MAX_LENGTH_RECIPES_NAME = 256
STR_LENGTH = 31
MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
