# Generated by Django 5.2.6 on 2025-10-04 16:59

import django.core.validators
from django.db import migrations, models

import backend.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_account_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=64, unique=True, validators=[backend.validators.validate_username, django.core.validators.RegexValidator(message='Имя пользователя может содержать буквы, цифры, и некоторые знаки', regex='^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
