# Generated by Django 5.2.6 on 2025-10-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_subscribed',
        ),
    ]
