# Generated by Django 5.2.6 on 2025-10-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
    ]
