# Generated by Django 5.2.6 on 2025-10-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_account_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
